language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tschroedertlc/docker-react-site -f Dockerfile.dev .

script:
  - docker run -e CI=true tschroedertlc/docker-react-site yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-site"
  env: "DockerReactSite-env"
  bucket_name: "elasticbeanstalk-us-west-2-544468246667"
  bucket_path: "docker-react-site"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"