language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tschroedertlc/docker-react-site -f Dockerfile.dev .

script:
  - docker run -e CI=true tschroedertlc/docker-react-site yarn test